version: '3.1'

services:
  mongodb:
    image: mongo:8.0.1
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=etlConfig
      - MONGO_INITDB_ROOT_PASSWORD=etlPassword
      - MONGO_INITDB_DATABASE=configuration
    volumes:
      - ./data:/data/db