version: '3.1'

services:
  mongodb:
    image: mongo:8.0.1
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  postgres:
    image: postgres:16.4
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin