CREATE TABLE "staging_transform" (
  "id" SERIAL PRIMARY KEY,
  "cpu_id" INT,
  "gpu_id" INT,
  "brand_id" INT,
  "tempered_glass_id" INT,
  "battery_id" INT,
  "storage_id" INT,
  "bluetooth_id" INT,
  "port_charge_id" INT,
  "headset_type_id" INT,
  "back_cam_movie_id" INT,
  "design_id" INT,
  "material_id" INT,
  "contacts" VARCHAR,
  "security" VARCHAR,
  "special_feature" VARCHAR,
  "water_resistant" VARCHAR,
  "record" VARCHAR,
  "movie" VARCHAR,
  "music" VARCHAR,
  "network_mobile" VARCHAR,
  "sim" VARCHAR,
  "wifi" VARCHAR,
  "gps" VARCHAR,
  "other_connection" VARCHAR,
  "dimension_weight" VARCHAR,
  "date_created" TIMESTAMP WITHOUT TIME ZONE,
  "pricing" NUMERIC,
  "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE "staging" (
    id SERIAL PRIMARY KEY,
    name TEXT,
    pricing TEXT,
    os TEXT,
    cpu TEXT,
    speed_cpu TEXT,
    gpu TEXT,
    ram TEXT,
    storage TEXT,
    free_storage TEXT,
    contacts TEXT,
    back_cam_resolution TEXT,
    back_cam_movie TEXT,
    back_cam_flash TEXT,
    back_cam_features TEXT,
    front_cam_resolution TEXT,
    front_cam_features TEXT,
    screen_technology TEXT,
    screen_resolution TEXT,
    screen_size TEXT,
    max_brightness TEXT,
    tempered_glass TEXT,
    battery_size TEXT,
    battery_type TEXT,
    max_charge TEXT,
    battery_technology TEXT,
    security TEXT,
    special_feature TEXT,
    water_resistant TEXT,
    record TEXT,
    movie TEXT,
    music TEXT,
    network_mobile TEXT,
    sim TEXT,
    wifi TEXT,
    gps TEXT,
    bluetooth TEXT,
    port_charge TEXT,
    headset_type TEXT,
    other_connection TEXT,
    design TEXT,
    material TEXT,
    dimension_weight TEXT,
    date_created TEXT,
    brand TEXT
);